apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-demo
  template:
    metadata:
      labels:
        app: sre-demo
    spec:
      containers:
      - name: sre-demo
        image: venkatbalajiumashankar/sre-ci-cd-demo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sre-demo
spec:
  selector:
    app: sre-demo
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
